// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nobrzsuseoktpyamyttu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5vYnJ6c3VzZW9rdHB5YW15dHR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3NTY0NTQsImV4cCI6MjA3MTMzMjQ1NH0.AbDvfsjR_cZ1RNeHIIOwgq6cF9Ab59vAjBZ_w_g-pUo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});